// app.config.js — replaces app.json so we can read .env at build time.
// Anything under `extra` is available at runtime via expo-constants.

const REVERSED_CLIENT_ID = process.env.GOOGLE_IOS_REVERSED_CLIENT_ID;

module.exports = ({ config }) => ({
  ...config,
  name: 'PPL Exam Prep',
  slug: 'ppl-exam-prep',
  version: '0.2.0',
  // Build numbers are auto-incremented by EAS for production builds.
  // For preview/dev, override here when needed.
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.jukilo.pplexamprep',
    buildNumber: '1',
    usesAppleSignIn: true,
    // Info.plist additions
    infoPlist: {
      // Required by Apple — descriptions shown when iOS prompts the user.
      NSCameraUsageDescription:
        'PPL Exam Prep does not use the camera. This entry is here only because a dependency declares the capability.',
      NSPhotoLibraryUsageDescription:
        'PPL Exam Prep does not access photos. This entry is here only because a dependency declares the capability.',
      // Allow Google Sign-In's URL scheme to call back into the app.
      // The CFBundleURLSchemes array gets merged with Expo's defaults.
      CFBundleURLTypes: [
        {
          CFBundleURLSchemes: [
            // Custom scheme for deep links (signup confirmation, etc.)
            'pplexamprep',
            // Google Sign-In reversed client ID (e.g. com.googleusercontent.apps.123-abc).
            // Filled at build time from .env. Empty fallback won't match anything,
            // so Google sign-in will simply fail to return — easier to debug than a crash.
            REVERSED_CLIENT_ID || 'com.googleusercontent.apps.invalid',
          ],
        },
      ],
      // Allows running on the simulator (signed builds only).
      ITSAppUsesNonExemptEncryption: false,
    },
    config: {
      // Reversed iOS client ID — used by Google Sign-In as a URL scheme.
      googleSignIn: {
        reservedClientId: REVERSED_CLIENT_ID,
      },
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#FFD89C',
    },
    package: 'com.jukilo.pplexamprep',
    versionCode: 1,
  },
  orientation: 'portrait',
  icon: './assets/icon.png',
  scheme: 'pplexamprep',
  userInterfaceStyle: 'light',
  splash: {
    image: './assets/splash.png',
    resizeMode: 'cover',
    backgroundColor: '#FFD89C',
  },
  assetBundlePatterns: ['**/*'],
  web: {
    favicon: './assets/favicon.png',
  },
  plugins: [
    'expo-apple-authentication',
    [
      '@react-native-google-signin/google-signin',
      {
        // Required by the plugin. When env var isn't set (e.g. running `eas`
        // commands without sourcing .env), use a placeholder so the config
        // can still parse. Real value is required for actual builds.
        iosUrlScheme: REVERSED_CLIENT_ID || 'com.googleusercontent.apps.placeholder',
      },
    ],
    'expo-font',
  ],
  extra: {
    supabaseUrl: process.env.SUPABASE_URL,
    supabaseAnonKey: process.env.SUPABASE_ANON_KEY,
    googleWebClientId: process.env.GOOGLE_WEB_CLIENT_ID,
    googleIosClientId: process.env.GOOGLE_IOS_CLIENT_ID,
    // Hard-coded — generated by `eas init`. Stable for the life of the project.
    eas: {
      projectId: 'f3a5f9bc-e0d6-41d6-92d3-d4038411bf1e',
    },
  },
  owner: 'jukilo',
});
